{% set version = "0.31.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-git2r
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/git2r_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/git2r/git2r_{{ version }}.tar.gz
  sha256: f1db9278fa4604600a64beaedcf86dda595d7c8a10cdb1f7300a6635e73cd66d

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - gnuconfig                    # [unix]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - libgit2                      # [not win]
    - libssh2
    - openssl
    - zlib
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - libssh2
    - openssl
    - zlib

test:
  commands:
    - $R -e "library('git2r')"           # [not win]
    - "\"%R%\" -e \"library('git2r')\""  # [win]

about:
  home: https://docs.ropensci.org/git2r/ (website), https://github.com/ropensci/git2r
  license: GPL-2.0-only
  summary: Interface to the 'libgit2' library, which is a pure C implementation of the 'Git' core methods. Provides access to 'Git' repositories to extract data and running some basic 'Git' commands.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - colinbrislawn
    - conda-forge/r
    - jdblischak
