appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: rHc1M/Cbwhu1ireUYmrcKKHvg7YDijFrFVfwm5ORq5G8oFpnfal8EL4VISlGUoFHQrt0FNJtel4AlQzBYyxEvsC6VBu6/IODpL+eVRoEjPI2F7bR0y47PB48pEFth9K9bbShjWxOIU/1Pz0jIvwi8uWR12hyvLc2QVHLKNSIa/YJJrF3ERJeJi43anF/vP4KTvCbzNr/mbEMJM+0nmfKxTS2qc3OyFBlmoucHtsorWhqXKEisji5H5qqf4bDGLocJWGwNECCv1ygIkK1Geclz2ofPrZ/cAdaNTvkVMukxChvAWM+ljTsxxWGd1DbfLRNqp+2eU8nZnFcy1LhGI77AID/DRoMExxt7dV7ZgwNEvm2q2zBzJvm7pA+C7vLbOm4a/6QzN7EW82ycVGU9dtFup91jhGPf/rUze2nIZQa+BbPvWEGDGyw7Npu8Q7uOjVyqLoG7YaCDmmWP2oego8Z/KzLyII1Q+jLI5jPYmezCJVn5zkggMguZLWLTExsKZ6zwn3HhRF8H6GgTfoyRaBWREX7jI3uh4CXfSg3Wp14zJ2AlB4o8EUTmmmw/zOwTaQZ/kkckjmbVlqoVJB6I7LDIEQXPQ6SrOGxjuxuR1/1cjdI/o42Z67dp8yQBvjbttBzK/t+zeIENXk8mbcIEJIP4i8CXvhHqLligh8sVlbyD2w=
conda_forge_output_validation: true
